package reactive;


public enum Tid 
{
	//-- slick 
	SCALA_ENTITY,     			// the case that correspond with model entity row class
	SCALA_ENTITY_DAOBASE, 		
	SCALA_ENTITY_DAOBASE_NORMAL,
	SCALA_ENTITY_DAOBASE_BASECLS,
	SCALA_ENTITY_DAOBASE_SUBSCLS,
	SCALA_ENTITY_DAO,
	SCALA_ENTITY_MOCK,
	SCALA_TEST_ENTITY_DAO,
	SCALA_TEST_ENTITY_MAPPERS,
	SCALA_ENUM,
	
	//-- akka
	SCALA_DAO_REQHANDLER,
	SCALA_DAO_SERVICE_INTF,
	SCALA_DAO_SERVICE_IMPL,
	SCALA_DAO_SERVICE_FACT,
	SCALA_DAO_SERVICE_MOCK,
	SCALA_DAO_SERVICE_ACTOR,
	SCALA_SERVICE_INTF,
	SCALA_SERVICE_IMPL,
	SCALA_SERVICE_FACT,
	SCALA_SERVICE_MOCK,
	SCALA_SERVICE_ACTOR,
	SCALA_SERVICE_REQHANDLER,
	
	//-- Dto
	SCALA_DTO,
	SCALA_DTO_MOCK,
	
	//-- scala appbase
	SCALA_SLICK_PROFILE,
	SCALA_SLICK_DATASOURCE,
	SCALA_VALIDATE_MODEL,
	SCALA_APP_CONFIG,
	SCALA_APP_DATASTORES,
	SCALA_APP_STARTUP,
	SCALA_APP_MAIN,
	SCALA_APP_ROUTE,
	SCALA_APP_CONSTANTS,
	SCALA_APP_STATICROUTE,
	SCALA_APP_JSON_MOCKS,
	
	//---scala common
	SCALA_ZIP_RESOURCE,

//	SCALA_APP_SBT,
	SCALA_BASECLASS,
	SCALA_ROWMAPPERS,
//	SCALA_LOGGER,
	SCALA_AKKA_SETTINGS,
	SCALA_CREATION_SUPPORT,
	SCALA_JSONUTILS,
	SCALA_RANDOMUTILS,
	
	//-- dojo --
	DOJO_ENTITY,
	DOJO_DTO,
	DOJO_ENUM,
	DOJO_ENTITY_DETAIL,
	DOJO_ENTITY_BROWSE,
	DOJO_ENTITY_SEARCH,
	DOJO_ENTITY_CONTROLLER,
	DOJO_SERVICE,
	DOJO_SERVICE_IMPL,
	DOJO_TEST_SERVICES,
	DOJO_DAO_SERVICE,
	DOJO_WIDGET_HTML,
	DOJO_WIDGET_JS,	
	DOJO_APP_CONSTANTS,
	DOJO_APP_MAIN,
	DOJO_APP_LEFTTREE,
	DOJO_APP_BASECTRL,
	DOJO_APP_TREE_JSON,
	DOJO_APP_INDEX,
	DOJO_APP_CSS,

	
	//-- Dart --
	DART_ENTITY,
	DART_DTO,
	DART_ENUM,
	DART_ENTITY_FORM,
	DART_ENTITY_FORM_HTML,
	DART_ENTITY_BROWSE,
	DART_ENTITY_BROWSE_HTML,
	DART_ENTITY_SEARCH,
	DART_ENTITY_SEARCH_HTML,
	DART_ENTITY_CTRL,
	DART_SERVICE,
	DART_SERVICE_IMPL,
	DART_TEST_SERVICES,
	DART_DAO_SERVICE,
	DART_APP_CONSTANTS,
	DART_APP_SERVICE_BASE,
	DART_APP_LEFTTREE,
	DART_APP_LIBRARY,
	DART_APP_MAINCTRL,
	DART_APP_ZIP_FILE,
	DART_APP_COMPONENTS,
	;

	
}
