package reactive.dart;

import java.util.*;
import java.lang.reflect.*;
import mda.type.*;
import flca.mda.api.util.*;
import flca.mda.codegen.helpers.*;
import reactive.*;

public class DartEntityController
{
  protected static String nl;
  public static synchronized DartEntityController create(String lineSeparator)
  {
    nl = lineSeparator;
    DartEntityController result = new DartEntityController();
    nl = null;
    return result;
  }

  public final String NL = nl == null ? (System.getProperties().getProperty("line.separator")) : nl;
  protected final String TEXT_1 = "library ";
  protected final String TEXT_2 = ".";
  protected final String TEXT_3 = ";" + NL + " " + NL + "import '";
  protected final String TEXT_4 = "';" + NL + "" + NL + "class ";
  protected final String TEXT_5 = " {" + NL + "" + NL + "  static ";
  protected final String TEXT_6 = " _instance = null;" + NL;
  protected final String TEXT_7 = NL + "  ";
  protected final String TEXT_8 = " _";
  protected final String TEXT_9 = ";" + NL + "" + NL + "  factory ";
  protected final String TEXT_10 = "() {" + NL + "    if (_instance == null) _instance = new ";
  protected final String TEXT_11 = "._newInstance();" + NL + "    return _instance;" + NL + "  }" + NL;
  protected final String TEXT_12 = NL + "  ";
  protected final String TEXT_13 = "._newInstance() {" + NL + "    Pubsub.subscribe(";
  protected final String TEXT_14 = ".";
  protected final String TEXT_15 = "_FINDALL, (PubsubMessage msg) {" + NL + "      _startBrowse();" + NL + "    });" + NL + "  }" + NL + "" + NL + "  void _startBrowse() {";
  protected final String TEXT_16 = NL + "    ";
  protected final String TEXT_17 = ".findAll";
  protected final String TEXT_18 = "(_handleFindAll);" + NL + "  }" + NL + "" + NL + "  void _onStartEdit(Event me, var detail, Node target) {" + NL + "    DivElement div = target;" + NL + "    print(\"index = \" + div.id);";
  protected final String TEXT_19 = NL + "    ";
  protected final String TEXT_20 = ".retrieve";
  protected final String TEXT_21 = "(div.id, _handleRetrieve";
  protected final String TEXT_22 = ");" + NL + "  }" + NL + "" + NL + "  void _onDoSubmit(";
  protected final String TEXT_23 = " ";
  protected final String TEXT_24 = ") {";
  protected final String TEXT_25 = NL + "    ";
  protected final String TEXT_26 = ".save";
  protected final String TEXT_27 = "(";
  protected final String TEXT_28 = ", _handleSave";
  protected final String TEXT_29 = ");" + NL + "  }" + NL + "  " + NL + "  void _handleSave";
  protected final String TEXT_30 = "(data) {" + NL + "//    print(\"_handleSave";
  protected final String TEXT_31 = " \" + data);" + NL + "    var ";
  protected final String TEXT_32 = " = new ";
  protected final String TEXT_33 = ".fromJson(data);" + NL + "    _showForm(";
  protected final String TEXT_34 = ");" + NL + "    print(\"_handleRetrieve";
  protected final String TEXT_35 = " \" + ";
  protected final String TEXT_36 = ".toString());" + NL + "  }" + NL + "  " + NL + "  void _handleFindAll(data) {" + NL + "    //    print(\"_handleFindAll \" + data);" + NL + "    _showGrid(data);" + NL + "  }" + NL + "" + NL + "  void _handleRetrieve";
  protected final String TEXT_37 = "(data) {" + NL + "    print(\"_handleRetrieve";
  protected final String TEXT_38 = " \" + data);" + NL + "    var ";
  protected final String TEXT_39 = " = new ";
  protected final String TEXT_40 = ".fromJson(data);" + NL + "    _showForm(";
  protected final String TEXT_41 = ");" + NL + "    print(\"_handleRetrieve";
  protected final String TEXT_42 = " \" + ";
  protected final String TEXT_43 = ".toString());" + NL + "  }" + NL + "" + NL + "  void _showGrid(data) {";
  protected final String TEXT_44 = NL + "    ";
  protected final String TEXT_45 = " view = new Element.tag('";
  protected final String TEXT_46 = "-browse');" + NL + "    List<String> rows = JSON.decode(data);" + NL + "    view.records = rows;" + NL + "    view.clickEdit = _onStartEdit;" + NL + "    MainView.instance().showContent(view);" + NL + "  }" + NL + "" + NL + "  void _showForm(";
  protected final String TEXT_47 = ") {";
  protected final String TEXT_48 = NL + "    ";
  protected final String TEXT_49 = " view = new Element.tag('";
  protected final String TEXT_50 = "-form');" + NL + "    view.";
  protected final String TEXT_51 = " = ";
  protected final String TEXT_52 = ";" + NL + "    view.submitHandler = _onDoSubmit;" + NL + "    MainView.instance().showContent(view);" + NL + "  }" + NL;
  protected final String TEXT_53 = NL + "  ";
  protected final String TEXT_54 = " get ";
  protected final String TEXT_55 = " {" + NL + "    if (_";
  protected final String TEXT_56 = " == null) _";
  protected final String TEXT_57 = " = new ";
  protected final String TEXT_58 = "();" + NL + "    return _";
  protected final String TEXT_59 = ";" + NL + "  }" + NL + "} ";

  public String generate(Object argument)
  {
    final StringBuffer stringBuffer = new StringBuffer();
     	// here we parse the input argument(s) and create the object JetArgument:arg and Object[]:args
	JetArgument arg = null;
	Object args[] = null;
	 
	if (argument != null) { 
		if (argument instanceof JetArgument) {
			arg = (JetArgument) argument;
		} else if (argument.getClass().isArray()) { 
			args = (Object[]) argument;
			if (args[0] instanceof JetArgument) {
				arg = (JetArgument) args[0];
			}
		}
	} 

     DartTypeUtils tu = new DartTypeUtils();
     ScalaInterfaceUtils iu = new ScalaInterfaceUtils(); 
     FilenameHelper fnh = new FilenameHelper(); 
     NameUtils nu = new NameUtils();
     TemplateUtils tplu = new TemplateUtils();
     AppUtils au = new AppUtils(); 
     Object element = arg.getElement(); 
     Class cc = element.getClass(); 
     String classname = nu.getCurrentClassname();
     String pck = nu.getCurrentPackage();
     String entity = tplu.getClassName(Tid.DART_ENTITY.name());
     String capname = nu.capName(entity); 
     String uncapname = nu.uncapName(entity); 
     String entityUC = entity.toUpperCase(); 
     String entityLC = entity.toLowerCase(); 
     boolean isSubClass = tu.isSubClass(cc); 
     boolean hasSubClasses = tu.hasSubClasses(cc); 
     boolean isBaseClass = tu.isBaseClass(cc); 
     boolean isAbstract = tu.hasAbstractAnnotation(); 
     String idname = tu.getIdName(cc); String idtype = tu.getIdTypeName(); 
     String pkName = nu.capName(tu.getIdName(cc)); String pkType = tu.getIdTypeName(); 
     String browseForm = tplu.getClassName(Tid.DART_ENTITY_BROWSE.name()); 
     String detailForm = tplu.getClassName(Tid.DART_ENTITY_FORM.name()); 
     String searchform = tplu.getClassName(Tid.DART_ENTITY_SEARCH.name());
     String daoservice = tplu.getClassName(Tid.DART_DAO_SERVICE.name());
     String appname = au.getApplicationName(); 
     String appConstants = tplu.getAppClassName(Tid.DART_APP_CONSTANTS.name());
     String serviceBase = tplu.getClassName(Tid.DART_APP_SERVICE_BASE.name());
     String pubpath = fnh.getRelativeToRootPath(element.getClass(), arg.getTemplate()) + "pub"; 
     String dartlib = fnh.getRelativeToRootPath(element.getClass(), arg.getTemplate()) + appname.toLowerCase() + "_library.dart"; 
     GetFieldsModus EXC = GetFieldsModus.EXCLUDE; 
     GetFieldsModus INC = GetFieldsModus.INCLUDE; 
     FwSelectType ID_FLD = FwSelectType.ID; 
     FwSelectType VAL_FLD = FwSelectType.VAL; 
     FwSelectType VAR_FLD = FwSelectType.VAR; 
     FwSelectType O2M_FLD = FwSelectType.ONETOMANY; 
     FwSelectType M2M_FLD = FwSelectType.MANYTOMANY; 
     FwSelectType M2O_FLD = FwSelectType.MANYTOONE; 
     FwSelectType O2O_FLD = FwSelectType.ONETOONE; 
     FwSelectType REL_FLD = FwSelectType.RELATIONS; 
     FwSelectType OFD_FLD = FwSelectType.OFD; 
     FwSelectType DISC_FLD = FwSelectType.DISCRIMINATOR; 
     FwSelectType SIMPLE_FLD = FwSelectType.SIMPLE; 
     FwSelectType ENUM_FLD = FwSelectType.ENUM; 
     FwSelectType SPECIAL_FLD = FwSelectType.SPECIAL; 
     String daosrv = nu.uncapName(daoservice); 
     if (!tu.hasAnnotation(cc, mda.annotation.RestService.class)) return ""; 
    stringBuffer.append(TEXT_1);
    stringBuffer.append(pck);
    stringBuffer.append(TEXT_2);
    stringBuffer.append(classname);
    stringBuffer.append(TEXT_3);
    stringBuffer.append(dartlib);
    stringBuffer.append(TEXT_4);
    stringBuffer.append(classname);
    stringBuffer.append(TEXT_5);
    stringBuffer.append(classname);
    stringBuffer.append(TEXT_6);
    stringBuffer.append(TEXT_7);
    stringBuffer.append(daoservice);
    stringBuffer.append(TEXT_8);
    stringBuffer.append(daosrv);
    stringBuffer.append(TEXT_9);
    stringBuffer.append(classname);
    stringBuffer.append(TEXT_10);
    stringBuffer.append(classname);
    stringBuffer.append(TEXT_11);
    stringBuffer.append(TEXT_12);
    stringBuffer.append(classname);
    stringBuffer.append(TEXT_13);
    stringBuffer.append(appConstants);
    stringBuffer.append(TEXT_14);
    stringBuffer.append(entityUC);
    stringBuffer.append(TEXT_15);
    stringBuffer.append(TEXT_16);
    stringBuffer.append(daosrv);
    stringBuffer.append(TEXT_17);
    stringBuffer.append(entity);
    stringBuffer.append(TEXT_18);
    stringBuffer.append(TEXT_19);
    stringBuffer.append(daosrv);
    stringBuffer.append(TEXT_20);
    stringBuffer.append(entity);
    stringBuffer.append(TEXT_21);
    stringBuffer.append(entity);
    stringBuffer.append(TEXT_22);
    stringBuffer.append(entity);
    stringBuffer.append(TEXT_23);
    stringBuffer.append(uncapname);
    stringBuffer.append(TEXT_24);
    stringBuffer.append(TEXT_25);
    stringBuffer.append(daosrv);
    stringBuffer.append(TEXT_26);
    stringBuffer.append(entity);
    stringBuffer.append(TEXT_27);
    stringBuffer.append(uncapname);
    stringBuffer.append(TEXT_28);
    stringBuffer.append(entity);
    stringBuffer.append(TEXT_29);
    stringBuffer.append(entity);
    stringBuffer.append(TEXT_30);
    stringBuffer.append(entity);
    stringBuffer.append(TEXT_31);
    stringBuffer.append(uncapname);
    stringBuffer.append(TEXT_32);
    stringBuffer.append(entity);
    stringBuffer.append(TEXT_33);
    stringBuffer.append(uncapname);
    stringBuffer.append(TEXT_34);
    stringBuffer.append(entity);
    stringBuffer.append(TEXT_35);
    stringBuffer.append(uncapname);
    stringBuffer.append(TEXT_36);
    stringBuffer.append(entity);
    stringBuffer.append(TEXT_37);
    stringBuffer.append(entity);
    stringBuffer.append(TEXT_38);
    stringBuffer.append(uncapname);
    stringBuffer.append(TEXT_39);
    stringBuffer.append(entity);
    stringBuffer.append(TEXT_40);
    stringBuffer.append(uncapname);
    stringBuffer.append(TEXT_41);
    stringBuffer.append(entity);
    stringBuffer.append(TEXT_42);
    stringBuffer.append(uncapname);
    stringBuffer.append(TEXT_43);
    stringBuffer.append(TEXT_44);
    stringBuffer.append(browseForm);
    stringBuffer.append(TEXT_45);
    stringBuffer.append(uncapname);
    stringBuffer.append(TEXT_46);
    stringBuffer.append(uncapname);
    stringBuffer.append(TEXT_47);
    stringBuffer.append(TEXT_48);
    stringBuffer.append(detailForm);
    stringBuffer.append(TEXT_49);
    stringBuffer.append(uncapname);
    stringBuffer.append(TEXT_50);
    stringBuffer.append(uncapname);
    stringBuffer.append(TEXT_51);
    stringBuffer.append(uncapname);
    stringBuffer.append(TEXT_52);
    stringBuffer.append(TEXT_53);
    stringBuffer.append(daoservice);
    stringBuffer.append(TEXT_54);
    stringBuffer.append(nu.uncapName(daosrv));
    stringBuffer.append(TEXT_55);
    stringBuffer.append(daosrv);
    stringBuffer.append(TEXT_56);
    stringBuffer.append(daosrv);
    stringBuffer.append(TEXT_57);
    stringBuffer.append(daoservice);
    stringBuffer.append(TEXT_58);
    stringBuffer.append(daosrv);
    stringBuffer.append(TEXT_59);
    return stringBuffer.toString();
  }
}
